# base url for production and staging domains
domains:
  production: https://www-origin.publishing.service.gov.uk
  staging: https://www-origin.staging.publishing.service.gov.uk

# Enter a list of pages that arent in the search system and would otherwise be omitted
hard_coded_pages:
  - /browse
  - /browse/benefits

verbose: false

page_indexer:
  # The maximum number of formats to search for.
  # There are less than 100, so a value of 100 will ensure we capture them all
  max_formats: 100

  # The maximum number of pages for each format
  max_pages_per_format: 4
